name: Build docker image
on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
      - 'v*.*.*'
      - '*.*.*-*'
      - 'v*.*.*-*'
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
      - src/**
      - project.clj
      - native-config/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build -t rinx/substrate-sample . --build-arg GRAALVM_VERSION=${GRAALVM_VERSION}
      env:
        GRAALVM_VERSION: '19.3.0'
    - name: Login to DockerHub
      run: |
        echo ${DOCKERHUB_PASS} | docker login --username ${DOCKERHUB_USER} --password-stdin
      env:
        DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
        DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    - name: push to DockerHub
      run: |
        docker push rinx/substrate-sample
